In [27]:
#importing library
import numpy as np

In [28]:
list1 = [1,2,3,4]

In [29]:
#multiplying all elements in list1 by 6
for i in range(len(list1)):
    list1[i] = (list1[i]*6)
print(list1)

[6, 12, 18, 24]


In [31]:
#creating a numpy array from a list
arr = np.array(list1)
print(arr)
type(arr)

[ 6 12 18 24]


numpy.ndarray

In [32]:
arr*10

array([ 60, 120, 180, 240])

In [34]:
mat = np.array([[1,2,3],[4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [40]:
matx = np.zeros((5,5))
print(matx)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [43]:
#creating a 10x10 matrix with all numbers equal to 6
mat1 = np.ones((10,10))*6
print(mat1)

[[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]]


In [51]:
arr1  = np.random.randint(0,100,(10,10))
print(arr1)

[[ 7 10 82 46 89 31  3 36 28 94]
 [50 66 36 73 54  0 72  0 27 62]
 [48 93 69 18 63 40 50 41 38 81]
 [18 17 67 65 88 71 91 25 96 17]
 [84 70 70 77 63 30 66  8 18 71]
 [17 27 97 42 33  3 60 26 36 28]
 [18 23 55  3 48 12 90 68 40 46]
 [63 42 12 70 69 29 15 82 96 33]
 [70 32 60 17 35 77 13 93 74 29]
 [68 22 29 85 88  7 82 70 35 95]]


In [55]:
# finding max and min 
print(arr1.max())
print(arr1.min())

97
0


In [56]:
#finding location of max and min
print(arr1.argmax())
print(arr1.argmin())

52
15


In [59]:
arr1.shape

(10, 10)

In [67]:
#reshaping array
arr2 = arr1.reshape((1,100))
arr2.shape

(1, 100)

In [70]:
#indexing and slicing
m1 = np.arange(0,100).reshape((10,10))
print(m1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [71]:
#locating an element in a particular row and column
m1[5,6]

56

In [74]:
#locating the last element in the matrix
m1[9,9]

99

In [77]:
#to get all elements of row 4
m1[3,0:10]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [83]:
#getting all rows and all columns
m1[::]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [86]:
m1[0:10,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [89]:
m1[4:9,2:8]

array([[42, 43, 44, 45, 46, 47],
       [52, 53, 54, 55, 56, 57],
       [62, 63, 64, 65, 66, 67],
       [72, 73, 74, 75, 76, 77],
       [82, 83, 84, 85, 86, 87]])

In [93]:
# assigning certain group of values to 0
m1[4:9,2:8] = 0
print(m1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41  0  0  0  0  0  0 48 49]
 [50 51  0  0  0  0  0  0 58 59]
 [60 61  0  0  0  0  0  0 68 69]
 [70 71  0  0  0  0  0  0 78 79]
 [80 81  0  0  0  0  0  0 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
